# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0f1e20895c5a87c3bc2826885d2e0264dff777c66aeb56a4c6f531d189e5ad76816fa63d21edda10a06b0774deb25e6929cc8792f5b4552c326771b66414789

test:
  secret_key_base: ee6069bd5f66d154e30d0cd9ac3cf9c7f91b008a2f4c64aa94df99c8ed276d69e798c7c09f96554440ba361c6b9c9a8d06935df2e39adf3675e29393bec78ef3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
